// require schema
const category = [
  { name: schema.html },
  { name: schema.css },
  { name: schema.javascript },
  { name: schema.typescript },
  { name: schema.nodejs },
  { name: schema.java },
  { name: schema.python },
  { name: schema.go },
  { name: schema.c },
  { name: schema.cpp },
  { name: schema.csharp },
  { name: schema.rust },
  { name: schema.linux },
  { name: schema.kali },
  { name: schema.docker },
  { name: schema.database },
  { name: schema.server },
  { name: schema.cloud },
  { name: schema.ide },
  { name: schema.git },
  { name: schema.etc },
];
