const contents = [
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html4...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "html3...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  {
    title: "javascript test!!",
    depth1: schema.javascript,
    depth2: schema.javascript,
    fileName: "test.html",
  },
  {
    title: "html2...",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "",
  },
  { title: "", depth1: schema.linux, depth2: schema.linux, fileName: "" },
  { title: "", depth1: schema.kali, depth2: schema.kali, fileName: "" },
  { title: "", depth1: schema.docker, depth2: schema.docker, fileName: "" },
  {
    title: "",
    depth1: schema.database,
    depth2: schema.database,
    fileName: "",
  },
  { title: "", depth1: schema.server, depth2: schema.server, fileName: "" },
  { title: "", depth1: schema.ide, depth2: schema.ide, fileName: "" },
  { title: "", depth1: schema.git, depth2: schema.git, fileName: "" },
  { title: "", depth1: schema.etc, depth2: schema.etc, fileName: "" },
];
