const contents = [
  {
    title: "html",
    depth1: schema.html,
    depth2: schema.html,
    fileName: "html.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "css",
    depth1: schema.css,
    depth2: schema.css,
    fileName: "css.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "javascript",
    depth1: schema.javascript,
    depth2: schema.javascript,
    fileName: "javascript.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "angular",
    depth1: schema.javascript,
    depth2: schema.angular,
    fileName: "angular.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "react",
    depth1: schema.javascript,
    depth2: schema.react,
    fileName: "react.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "react-native",
    depth1: schema.javascript,
    depth2: schema.reactNative,
    fileName: "react-native.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "vue",
    depth1: schema.javascript,
    depth2: schema.vue,
    fileName: "vue.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "grunt",
    depth1: schema.javascript,
    depth2: schema.grunt,
    fileName: "grunt.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "webpack",
    depth1: schema.javascript,
    depth2: schema.webpack,
    fileName: "webpack.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "gulp",
    depth1: schema.javascript,
    depth2: schema.gulp,
    fileName: "gulp.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "typescript",
    depth1: schema.javascript,
    depth2: schema.typescript,
    fileName: "typescript.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "threejs",
    depth1: schema.javascript,
    depth2: schema.threejs,
    fileName: "threejs.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "amcharts",
    depth1: schema.javascript,
    depth2: schema.amcharts,
    fileName: "amcharts.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "jquery",
    depth1: schema.javascript,
    depth2: schema.jquery,
    fileName: "jquery.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "nodejs",
    depth1: schema.nodejs,
    depth2: schema.nodejs,
    fileName: "nodejs.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "express",
    depth1: schema.nodejs,
    depth2: schema.express,
    fileName: "express.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "graphql",
    depth1: schema.nodejs,
    depth2: schema.graphql,
    fileName: "graphql.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "nestjs",
    depth1: schema.nodejs,
    depth2: schema.nestjs,
    fileName: "nestjs.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "sockeio",
    depth1: schema.nodejs,
    depth2: schema.socketio,
    fileName: "socketio.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "java",
    depth1: schema.java,
    depth2: schema.java,
    fileName: "java.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "spring",
    depth1: schema.java,
    depth2: schema.spring,
    fileName: "spring.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "spring boot",
    depth1: schema.java,
    depth2: schema.springboot,
    fileName: "springboot.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "my batis",
    depth1: schema.java,
    depth2: schema.mybatis,
    fileName: "mybatis.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "maven",
    depth1: schema.java,
    depth2: schema.maven,
    fileName: "maven.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "gradle",
    depth1: schema.java,
    depth2: schema.gradle,
    fileName: "gradle.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "android",
    depth1: schema.java,
    depth2: schema.android,
    fileName: "android.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "python",
    depth1: schema.python,
    depth2: schema.python,
    fileName: "python.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "django",
    depth1: schema.python,
    depth2: schema.django,
    fileName: "django.htm",
    desc: "",
    date: "20201126",
  },
  {
    title: "go",
    depth1: schema.go,
    depth2: schema.go,
    fileName: "go.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "c",
    depth1: schema.c,
    depth2: schema.c,
    fileName: "c.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "c++",
    depth1: schema.c,
    depth2: schema.cpp,
    fileName: "cpp.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "c#",
    depth1: schema.c,
    depth2: schema.csharp,
    fileName: "csharp.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "unity",
    depth1: schema.c,
    depth2: schema.unity,
    fileName: "unity.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "rust",
    depth1: schema.rust,
    depth2: schema.rust,
    fileName: "rust.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "linux",
    depth1: schema.linux,
    depth2: schema.linux,
    fileName: "linux.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "tmux",
    depth1: schema.linux,
    depth2: schema.linux,
    fileName: "tmux.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "vim",
    depth1: schema.linux,
    depth2: schema.vim,
    fileName: "vim.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "zsh",
    depth1: schema.linux,
    depth2: schema.zsh,
    fileName: "zsh.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "ssh",
    depth1: schema.linux,
    depth2: schema.ssh,
    fileName: "ssh.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "ssl",
    depth1: schema.linux,
    depth2: schema.ssl,
    fileName: "ssl.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "ubuntu",
    depth1: schema.linux,
    depth2: schema.ubuntu,
    fileName: "ubuntu.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "centos",
    depth1: schema.linux,
    depth2: schema.centos,
    fileName: "centos.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "kali",
    depth1: schema.kali,
    depth2: schema.kali,
    fileName: "kali.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "metasploit",
    depth1: schema.kali,
    depth2: schema.metasploit,
    fileName: "metasploit.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "wireshark",
    depth1: schema.kali,
    depth2: schema.wireshark,
    fileName: "wireshark.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "burpsuite",
    depth1: schema.kali,
    depth2: schema.burpsuite,
    fileName: "burpsuite.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "docker",
    depth1: schema.docker,
    depth2: schema.docker,
    fileName: "docker.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "kubernetes",
    depth1: schema.docker,
    depth2: schema.kubernetes,
    fileName: "kubernetes.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "database",
    depth1: schema.database,
    depth2: schema.database,
    fileName: "database.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "sql",
    depth1: schema.database,
    depth2: schema.sql,
    fileName: "sql.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "oracle",
    depth1: schema.database,
    depth2: schema.oracle,
    fileName: "oracle.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "mariadb",
    depth1: schema.database,
    depth2: schema.mariadb,
    fileName: "mariadb.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "nosql",
    depth1: schema.database,
    depth2: schema.nosql,
    fileName: "nosql.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "mongodb",
    depth1: schema.database,
    depth2: schema.mongodb,
    fileName: "mongodb.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "redis",
    depth1: schema.database,
    depth2: schema.redis,
    fileName: "redis.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "firebase",
    depth1: schema.database,
    depth2: schema.firebase,
    fileName: "firebase.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "server",
    depth1: schema.server,
    depth2: schema.server,
    fileName: "server.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "nginx",
    depth1: schema.server,
    depth2: schema.nginx,
    fileName: "nginx.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "apache",
    depth1: schema.server,
    depth2: schema.apache,
    fileName: "apache.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "cloud",
    depth1: schema.cloud,
    depth2: schema.cloud,
    fileName: "cloud.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "aws",
    depth1: schema.cloud,
    depth2: schema.aws,
    fileName: "aws.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "oracle cloud",
    depth1: schema.cloud,
    depth2: schema.oracleclude,
    fileName: "oraclecloud.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "ide",
    depth1: schema.ide,
    depth2: schema.ide,
    fileName: "ide.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "eclipse",
    depth1: schema.ide,
    depth2: schema.eclipse,
    fileName: "eclipse.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "vscode",
    depth1: schema.ide,
    depth2: schema.vscode,
    fileName: "vscode.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "git",
    depth1: schema.git,
    depth2: schema.git,
    fileName: "git.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "etc",
    depth1: schema.etc,
    depth2: schema.etc,
    fileName: "etc.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "architecture",
    depth1: schema.etc,
    depth2: schema.architecture,
    fileName: "architecture.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "network",
    depth1: schema.etc,
    depth2: schema.network,
    fileName: "network.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "hardware",
    depth1: schema.etc,
    depth2: schema.hardware,
    fileName: "hardware.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "algorithm",
    depth1: schema.etc,
    depth2: schema.algorithm,
    fileName: "algorithm.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "raspberrypi",
    depth1: schema.etc,
    depth2: schema.raspberrypi,
    fileName: "raspberrypi.htm",
    desc: "",
    date: "20201121",
  },
  {
    title: "rest",
    depth1: schema.etc,
    depth2: schema.rest,
    fileName: "rest.htm",
    desc: "",
    date: "20201121",
  },
];
